WIP: Postgresql driver
mikey-austin/greyd pull request #10
Opened 2016-09-25 11:38 UTC by rubberydub

There's still a bug in the scan function.

2016-09-25 11:41 UTC, rubberydub commented
I've checked the update statement in the scan function and it seems to be working fine. The select is returning one row less than the MySQL equivalent. I'll fix this over the next few days.

2016-09-27 07:48 UTC, mikey-austin requested changes

2016-09-27 07:48 UTC, mikey-austin commented on drivers/postgresql.c
> + * @author Mikey Austin
You should change this to be your name

2016-09-27 07:48 UTC, mikey-austin commented on drivers/postgresql.c
> + * Copyright (c) 2014, 2015 Mikey Austin <mikey@greyd.org>
Add yourself into the copyright

2016-09-30 23:47 UTC, rubberydub commented on drivers/postgresql.c
> + * Copyright (c) 2014, 2015 Mikey Austin <mikey@greyd.org>
Done

2016-09-30 23:47 UTC, rubberydub commented on drivers/postgresql.c
> + * @author Mikey Austin
Done

2016-10-02 04:08 UTC, rubberydub commented on drivers/postgresql.c
> +                                  strdup((const char *)
I am unsure how to break these long lines correctly.

2016-10-02 04:08 UTC, rubberydub commented on drivers/postgresql.c
> +                                         PQgetvalue(result, tuple, 0)));
I am unsure how to break these long lines correctly.

2016-10-02 04:42 UTC, rubberydub commented on drivers/postgresql.c
> +        "AND g.\"ip\" IS NULL";
The implicit join between the updated table and the table in the from clause is a natural join. As such, the previous update statement I gave was broken. This way fixes the issue by constructing the left self- join and then joining again (implicitly) on the primary key (lines 702 and 703).

Beyond the statement being ugly and confusing, I am still unsure as to what will happen if there is a conflict during the update. Postgres has no ignore modifier for updates.

There's the option of selecting and holding the rows, deleting them and then upserting them back. It seems like a bad idea.

2016-10-02 05:03 UTC, rubberydub commented on drivers/postgresql.c
> +        "AND g.\"ip\" IS NULL";
See [this](https://www.postgresql.org/docs/9.6/static/queries-with.html) (7.8.2).

The solution might be a statement which will delete the updated rows in a WITH query and upset them back with the appropriate changes. If there is a conflict, then insert the original row which was deleted.

2016-10-11 08:00 UTC, merged

2016-10-11 08:02 UTC, mikey-austin commented on drivers/postgresql.c
> +                                         PQgetvalue(result, tuple, 0)));
That is fine man

2016-10-11 08:03 UTC, mikey-austin commented on drivers/postgresql.c
> +        "AND g.\"ip\" IS NULL";
It would be great if you could make a test that exposes this exact issue, then we can compare against the other database drivers.

2016-10-11 08:05 UTC, mikey-austin commented
Also we need to update travis to build all database drivers. Which means we will then need to install and setup MySQL & Postgresql on the travis machine first.